apiVersion: v1
kind: Service
metadata:
  name: react-test-service
spec:
  selector: 
    app: react-app
  type: LoadBalancer
  ports: 
    - protocol: TCP
      port: 3000  # Port exposed by the service is 3000
      targetPort: 80  # Target port is 80 inside the container
